VehicleTrademark.create([
  { id: 1,  name_en: 'Audi', name_ua: 'Ауді' },
  { id: 2,  name_en: 'BMW', name_ua: 'БМВ' },
  { id: 3,  name_en: 'Daewoo', name_ua:'Деу' },
  { id: 4,  name_en: 'Ford', name_ua: 'Форд' },
  { id: 5,  name_en: 'Honda', name_ua: 'Хонда' },
  { id: 6,  name_en: 'Kia', name_ua: 'Кіа' },
  { id: 7,  name_en: 'Mazda', name_ua: 'Мазда' },
  { id: 8,  name_en: 'Mercedes', name_ua: 'Мерседес' },
  { id: 9,  name_en: 'Mitsubishi', name_ua: 'Мітсубіші' },
  { id: 10, name_en: 'Nissan', name_ua: 'Ніссан' },
  { id: 11, name_en: 'Opel', name_ua: 'Опель' },
  { id: 12, name_en: 'Peugeot', name_ua: 'Пежо' },
  { id: 13, name_en: 'Renault', name_ua: 'Рено' },
  { id: 14, name_en: 'SAAB', name_ua: 'СААБ' },
  { id: 15, name_en: 'Skoda', name_ua: 'Шкода' },
  { id: 16, name_en: 'Subaru', name_ua: 'Субару' },
  { id: 17, name_en: 'Toyota', name_ua: 'Тойота' },
  { id: 18, name_en: 'VAZ', name_ua: 'ВАЗ' },
  { id: 19, name_en: 'Volvo', name_ua: 'Вольво' },
  { id: 20, name_en: 'Volkswagen', name_ua: 'Фольксваген' },
  { id: 21, name_en: 'Fleet', name_ua: 'Fleet' },
  { id: 22, name_en: 'Fiat', name_ua: 'Фіат' },
  { id: 23, name_en: 'Hyundai', name_ua: 'Хюндай' },
  { id: 24, name_en: 'Citroen', name_ua: 'Сітроен' },
  { id: 25, name_en: 'Yale', name_ua: 'Ялі' },
  { id: 26, name_en: 'Seat', name_ua: 'Сеат' },
  { id: 27, name_en: 'Chevrolet', name_ua: 'Шевроле' },
  { id: 29, name_en: 'GAZ', name_ua: 'ГАЗ' },
  { id: 30, name_en: 'Lexus', name_ua: 'Лексус' },
  { id: 31, name_en: 'Dacia', name_ua: 'Дасіа' },
  { id: 32, name_en: 'Maserati', name_ua: 'Мазераті' },
  { id: 33, name_en: 'Suzuki', name_ua: 'Сузукі' },
  { id: 34, name_en: 'Land Rover', name_ua: 'Ленд Ровер' },
  { id: 35, name_en: 'ZAZ', name_ua: 'ЗАЗ' },
  { id: 36, name_en: 'Jaguar', name_ua: 'Ягуар' },
  { id: 37, name_en: 'Bogdan (tourist)', name_ua: 'Богдан (турист)' },
  { id: 38, name_en: 'Porsche', name_ua: 'Порше' },
  { id: 39, name_en: 'Iveco', name_ua: 'Івеко' },
  { id: 40, name_en: 'Chrysler', name_ua: 'Крайслер' },
  { id: 41, name_en: 'Ssang Yong', name_ua: 'Санг Йонг' },
  { id: 42, name_en: 'GM', name_ua: 'ГМ' },
  { id: 43, name_en: 'Mini', name_ua: 'Міні' },
  { id: 44, name_en: 'Jeep', name_ua: 'Джип' },
  { id: 45, name_en: 'Dodge', name_ua: 'Додж' },
  { id: 46, name_en: 'Infiniti', name_ua: 'Інфініті' },
  { id: 47, name_en: 'Acura', name_ua: 'Акура' },
  { id: 48, name_en: 'Izh', name_ua: 'ИЖ' },
  { id: 49, name_en: 'Komatsu', name_ua: 'Коматсу' },
  { id: 50, name_en: 'Alfa Romeo', name_ua: 'Альфа Ромео' },
  { id: 51, name_en: 'TATA', name_ua: 'TATA' },
  { id: 52, name_en: 'Cadilac', name_ua: 'Каділак' },
  { id: 53, name_en: 'Chery', name_ua: 'Чері' },
  { id: 54, name_en: 'UAZ', name_ua: 'УАЗ' },
  { id: 56, name_en: 'MAN', name_ua: 'МЕН' },
  { id: 57, name_en: 'Daihatsu', name_ua: 'Daihatsu' },
  { id: 61, name_en: 'Range', name_ua: 'Range' },
  { id: 62, name_en: 'Bogdan', name_ua: 'Богдан' },
  { id: 63, name_en: 'Santey', name_ua: 'Сантей' }
])
