VehicleModel.create([
{ id: 4, name_en: 'Fabia', name_ua: 'Фабія', vehicle_trademark_id: 15, vehicle_group_id: 2, wheel_count: 4 },
{ id: 5, name_en: 'A4', name_ua: 'A4', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 6, name_en: 'A6', name_ua: 'A6', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 7, name_en: 'X-5', name_ua: 'X-5', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 8, name_en: '525', name_ua: '525', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 9, name_en: 'Astra', name_ua: 'Астра', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 10, name_en: 'Ducato', name_ua: 'Ducato', vehicle_trademark_id: 22, vehicle_group_id: 3, wheel_count: 4 },
{ id: 11, name_en: 'Octavia', name_ua: 'Октавія', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 12, name_en: 'SuperB', name_ua: 'СуперБ', vehicle_trademark_id: 15, vehicle_group_id: 4, wheel_count: 4 },
{ id: 13, name_en: 'Golf 4', name_ua: 'Гольф 4', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 14, name_en: 'Bora', name_ua: 'Бора', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 16, name_en: 'Passat', name_ua: 'Пасcат', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 17, name_en: 'Golf 5', name_ua: 'Гольф 5', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 18, name_en: 'Polo', name_ua: 'Поло', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 19, name_en: 'Caddy Kasten', name_ua: 'Кеди Кастен', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 20, name_en: 'Transporter', name_ua: 'Транспортёр', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 21, name_en: 'Transporter Kаsten', name_ua: 'Транспортёр Кастен', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 22, name_en: 'Multivan', name_ua: 'Мультиван', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 23, name_en: 'Touran', name_ua: 'Туран', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 24, name_en: 'Sharan', name_ua: 'Шаран', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 25, name_en: 'Touareg', name_ua: 'Туарег', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 26, name_en: 'Phaeton', name_ua: 'Фаетон', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 27, name_en: 'Caddy', name_ua: 'Кеди', vehicle_trademark_id: 20, vehicle_group_id: nil, wheel_count: 4 },
{ id: 28, name_en: 'Caravelle', name_ua: 'Каравелла', vehicle_trademark_id: 20, vehicle_group_id: nil, wheel_count: 4 },
{ id: 29, name_en: 'T4 Kombi', name_ua: 'Т4 комби', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 30, name_en: 'Impreza', name_ua: 'Импреза', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 31, name_en: 'Legacy', name_ua: 'Легези', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 32, name_en: 'Forester', name_ua: 'Форестер', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 33, name_en: 'Legacy Outback', name_ua: 'Легези Аутбек', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 34, name_en: 'Symbol', name_ua: 'Символ', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 35, name_en: 'Clio', name_ua: 'Клио', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 36, name_en: 'Megane', name_ua: 'Меган', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 40, name_en: 'Scenic', name_ua: 'Сценик', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 41, name_en: 'Scenic 4x4', name_ua: 'Сценик 4x4', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 42, name_en: 'Laguna', name_ua: 'Лагуна', vehicle_trademark_id: 13, vehicle_group_id: 5, wheel_count: 4 },
{ id: 43, name_en: 'Espace', name_ua: 'Еспейc', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 44, name_en: 'Espace Grand', name_ua: 'Еспейс Гранд', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 45, name_en: 'Kangoo Express', name_ua: 'Кангу Експрес', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 46, name_en: 'Kangoo 4x4', name_ua: 'Кангу 4x4', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 47, name_en: 'Kangoo', name_ua: 'Кангу ', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 48, name_en: 'A8', name_ua: 'A8', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 50, name_en: 'A4 quattro', name_ua: 'A4 кватро', vehicle_trademark_id: 1, vehicle_group_id: nil, wheel_count: 4 },
{ id: 51, name_en: 'A6 quattro', name_ua: 'А6 кватро', vehicle_trademark_id: 1, vehicle_group_id: nil, wheel_count: 4 },
{ id: 52, name_en: 'A8 quattro', name_ua: 'А8 кватро', vehicle_trademark_id: 1, vehicle_group_id: nil, wheel_count: 4 },
{ id: 53, name_en: 'A3', name_ua: 'A3', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 54, name_en: 'allroad quattro', name_ua: 'алроад', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 55, name_en: 'TT quattro', name_ua: 'TT кватро', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 56, name_en: 'TT coupe', name_ua: 'TT купе', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 57, name_en: 'LT-46', name_ua: 'LT-46', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 58, name_en: 'Vectra', name_ua: 'Вектра', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 60, name_en: 'Omega', name_ua: 'Омега', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 61, name_en: 'Zafira', name_ua: 'Зафіра', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 62, name_en: 'Corsa', name_ua: 'Корса', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 63, name_en: 'Combo', name_ua: 'Комбо', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 64, name_en: 'Meriva', name_ua: 'Меріва', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 65, name_en: 'Movano', name_ua: 'Мовано', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 66, name_en: 'Almera', name_ua: 'Almera', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 67, name_en: 'Primera', name_ua: 'Primera', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 68, name_en: 'Maxima', name_ua: 'Maxima', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 69, name_en: 'Camry', name_ua: 'Camry', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 70, name_en: 'Land Cruiser 100', name_ua: 'Land Cruiser 100', vehicle_trademark_id: 17, vehicle_group_id: 5, wheel_count: 4 },
{ id: 71, name_en: 'Avensis', name_ua: 'Avensis', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 73, name_en: 'RAV 4', name_ua: 'RAV 4', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 74, name_en: 'Accord', name_ua: 'Accord', vehicle_trademark_id: 5, vehicle_group_id: 3, wheel_count: 4 },
{ id: 75, name_en: 'Civic', name_ua: 'Civic', vehicle_trademark_id: 5, vehicle_group_id: 3, wheel_count: 4 },
{ id: 76, name_en: 'Sonata', name_ua: 'Sonata', vehicle_trademark_id: 23, vehicle_group_id: 3, wheel_count: 4 },
{ id: 77, name_en: 'CR-V', name_ua: 'CR-V', vehicle_trademark_id: 5, vehicle_group_id: 3, wheel_count: 4 },
{ id: 78, name_en: 'X-Trail', name_ua: 'X-Trail', vehicle_trademark_id: 10, vehicle_group_id: 4, wheel_count: 4 },
{ id: 79, name_en: 'Corolla', name_ua: 'Corolla', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 80, name_en: '3', name_ua: '3', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 81, name_en: '323', name_ua: '323', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 82, name_en: '6', name_ua: '6', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 83, name_en: 'Aveo', name_ua: 'Авео', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 84, name_en: 'Matiz', name_ua: 'Матіз', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 85, name_en: 'Nubira 2', name_ua: 'Нубіра 2', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 86, name_en: 'Berlingo', name_ua: 'Берлінго', vehicle_trademark_id: 24, vehicle_group_id: 3, wheel_count: 4 },
{ id: 87, name_en: '730', name_ua: '730', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 88, name_en: 'Carisma', name_ua: 'Carisma', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 89, name_en: 'Lancer', name_ua: 'Lancer', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 90, name_en: 'Pajero Pinin', name_ua: 'Pajero Pinin', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 91, name_en: 'Pajero Sport', name_ua: 'Pajero Sport', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 92, name_en: 'Space Star', name_ua: 'Space Star', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 93, name_en: 'Pajero Wagon', name_ua: 'Pajero Wagon', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 94, name_en: 'Galant', name_ua: 'Galant', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 95, name_en: 'Ibiza', name_ua: 'Ibiza', vehicle_trademark_id: 26, vehicle_group_id: 3, wheel_count: 4 },
{ id: 96, name_en: 'Alhambra', name_ua: 'Alhambra', vehicle_trademark_id: 26, vehicle_group_id: 3, wheel_count: 4 },
{ id: 97, name_en: 'Premacy', name_ua: 'Premacy', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 98, name_en: '626', name_ua: '626', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 99, name_en: '323 LX', name_ua: '323 LX', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 100, name_en: '323 5HB', name_ua: '323 5HB', vehicle_trademark_id: 7, vehicle_group_id: 3, wheel_count: 4 },
{ id: 101, name_en: 'Lanos', name_ua: 'Lanos', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 102, name_en: 'Nexia', name_ua: 'Nexia', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 103, name_en: 'Espero', name_ua: 'Espero', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 104, name_en: 'Nubira', name_ua: 'Nubira', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 105, name_en: 'Tico', name_ua: 'Tico', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 106, name_en: 'S80', name_ua: 'S80', vehicle_trademark_id: 19, vehicle_group_id: 5, wheel_count: 4 },
{ id: 107, name_en: 'S60', name_ua: 'S60', vehicle_trademark_id: 19, vehicle_group_id: 3, wheel_count: 4 },
{ id: 108, name_en: 'S40', name_ua: 'S40', vehicle_trademark_id: 19, vehicle_group_id: 3, wheel_count: 4 },
{ id: 109, name_en: 'XC70', name_ua: 'XC70', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 110, name_en: 'S90', name_ua: 'S90', vehicle_trademark_id: 19, vehicle_group_id: 5, wheel_count: 4 },
{ id: 111, name_en: 'V70', name_ua: 'V70', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 112, name_en: 'Mondeo', name_ua: 'Мондео', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 },
{ id: 113, name_en: 'Focus 1', name_ua: 'Фокус 1', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 114, name_en: 'Transit', name_ua: 'Transit', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 115, name_en: 'Windstar', name_ua: 'Windstar', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 116, name_en: 'Escort', name_ua: 'Escort', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 117, name_en: 'Connect', name_ua: 'Connect', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 118, name_en: 'Felicia', name_ua: 'Felicia', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 119, name_en: '206', name_ua: '206', vehicle_trademark_id: 12, vehicle_group_id: 1, wheel_count: 4 },
{ id: 120, name_en: '306', name_ua: '306', vehicle_trademark_id: 12, vehicle_group_id: 2, wheel_count: 4 },
{ id: 121, name_en: '406', name_ua: '406', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 122, name_en: '307', name_ua: '307', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 123, name_en: '607', name_ua: '607', vehicle_trademark_id: 12, vehicle_group_id: 4, wheel_count: 4 },
{ id: 124, name_en: 'Boxer', name_ua: 'Boxer', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 125, name_en: 'E200 K', name_ua: 'E200 K', vehicle_trademark_id: 8, vehicle_group_id: 3, wheel_count: 4 },
{ id: 126, name_en: '21111', name_ua: '21111', vehicle_trademark_id: 18, vehicle_group_id: nil, wheel_count: 4 },
{ id: 127, name_en: '9-5', name_ua: '9-5', vehicle_trademark_id: 14, vehicle_group_id: 3, wheel_count: 4 },
{ id: 128, name_en: 'K2700', name_ua: 'K2700', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 129, name_en: 'Vito', name_ua: 'Vito', vehicle_trademark_id: 8, vehicle_group_id: 3, wheel_count: 4 },
{ id: 130, name_en: 'Expert', name_ua: 'Expert', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 131, name_en: 'Partner', name_ua: 'Partner', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 132, name_en: 'Sportage', name_ua: 'Sportage', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 135, name_en: 'GAZel 2705', name_ua: 'ГАЗель 2705', vehicle_trademark_id: 29, vehicle_group_id: 3, wheel_count: 4 },
{ id: 138, name_en: 'Focus C-Max', name_ua: 'Focus C-Max', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 139, name_en: 'Pick-up', name_ua: 'Pick-up', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 141, name_en: 'Astra H', name_ua: 'Astra H', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 142, name_en: 'LT-35', name_ua: 'LT-35', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 143, name_en: 'Lacetti', name_ua: 'Лачетті', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 144, name_en: 'YALE GLP 20 AF', name_ua: 'YALE GLP 20 AF', vehicle_trademark_id: 25, vehicle_group_id: 3, wheel_count: 4 },
{ id: 146, name_en: 'Outlander', name_ua: 'Outlander', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 147, name_en: 'Niva', name_ua: 'Ніва', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 149, name_en: 'Doblo Panorama', name_ua: 'Doblo Panorama', vehicle_trademark_id: 22, vehicle_group_id: 3, wheel_count: 4 },
{ id: 150, name_en: 'Lancer STW', name_ua: 'Lancer STW', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 151, name_en: 'Land Cruiser Prado120', name_ua: 'Land Cruiser Prado120', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 152, name_en: 'RX300', name_ua: 'RX300', vehicle_trademark_id: 30, vehicle_group_id: 3, wheel_count: 4 },
{ id: 153, name_en: 'Campo', name_ua: 'Кампо', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 155, name_en: '320', name_ua: '320', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 156, name_en: 'GAZel 33021', name_ua: 'ГАЗель 33021', vehicle_trademark_id: 29, vehicle_group_id: 3, wheel_count: 4 },
{ id: 157, name_en: 'E240', name_ua: 'E240', vehicle_trademark_id: 8, vehicle_group_id: nil, wheel_count: 4 },
{ id: 158, name_en: 'Fleet', name_ua: 'Fleet', vehicle_trademark_id: 21, vehicle_group_id: nil, wheel_count: 4 },
{ id: 159, name_en: 'Focus', name_ua: 'Фокус', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 160, name_en: 'Santa Fe', name_ua: 'Санта Фе', vehicle_trademark_id: 23, vehicle_group_id: 4, wheel_count: 4 },
{ id: 161, name_en: '2115', name_ua: '2115', vehicle_trademark_id: 18, vehicle_group_id: 2, wheel_count: 4 },
{ id: 162, name_en: 'S500 W/V221', name_ua: 'S500 W/V221', vehicle_trademark_id: 8, vehicle_group_id: nil, wheel_count: 4 },
{ id: 163, name_en: 'Octavia A5', name_ua: 'Октавія А5', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 164, name_en: 'IS 250', name_ua: 'IS 250', vehicle_trademark_id: 30, vehicle_group_id: 3, wheel_count: 4 },
{ id: 165, name_en: 'Elantra', name_ua: 'Elantra', vehicle_trademark_id: 23, vehicle_group_id: 3, wheel_count: 4 },
{ id: 166, name_en: 'Logan', name_ua: 'Logan', vehicle_trademark_id: 31, vehicle_group_id: 2, wheel_count: 4 },
{ id: 167, name_en: 'Getz', name_ua: 'Getz', vehicle_trademark_id: 23, vehicle_group_id: 2, wheel_count: 4 },
{ id: 168, name_en: 'Note', name_ua: 'Note', vehicle_trademark_id: 10, vehicle_group_id: 2, wheel_count: 4 },
{ id: 169, name_en: 'Navara', name_ua: 'Навара', vehicle_trademark_id: 10, vehicle_group_id: 4, wheel_count: 4 },
{ id: 170, name_en: 'Almera Classic', name_ua: 'Almera Classic', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 171, name_en: 'Murano', name_ua: 'Murano', vehicle_trademark_id: 10, vehicle_group_id: nil, wheel_count: 4 },
{ id: 172, name_en: 'Pathfinder', name_ua: 'Pathfinder', vehicle_trademark_id: 10, vehicle_group_id: 5, wheel_count: 4 },
{ id: 173, name_en: '350Z Coupe', name_ua: '350Z Coupe', vehicle_trademark_id: 10, vehicle_group_id: nil, wheel_count: 4 },
{ id: 174, name_en: 'Fiesta', name_ua: 'Фіеста', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 175, name_en: '5', name_ua: '5', vehicle_trademark_id: 7, vehicle_group_id: 4, wheel_count: 4 },
{ id: 176, name_en: 'Colt', name_ua: 'Кольт', vehicle_trademark_id: 9, vehicle_group_id: 2, wheel_count: 4 },
{ id: 177, name_en: 'Matrix', name_ua: 'Matrix', vehicle_trademark_id: 23, vehicle_group_id: 2, wheel_count: 4 },
{ id: 178, name_en: 'Passat B6', name_ua: 'Пассат Б6', vehicle_trademark_id: 20, vehicle_group_id: 4, wheel_count: 4 },
{ id: 179, name_en: 'Lanos T-150', name_ua: 'Lanos T-150', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 180, name_en: 'Modus', name_ua: 'Модус', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 181, name_en: 'Stream', name_ua: 'Стрім', vehicle_trademark_id: 5, vehicle_group_id: 3, wheel_count: 4 },
{ id: 182, name_en: 'Caddy Kombi', name_ua: 'Кеди комби', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 183, name_en: 'T5 Caravelle', name_ua: 'T5 Каравелла', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 184, name_en: 'Scenic 2', name_ua: 'Сценик 2', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 186, name_en: '21112', name_ua: '21112', vehicle_trademark_id: 18, vehicle_group_id: 3, wheel_count: 4 },
{ id: 188, name_en: '21214 Niva', name_ua: '21214 Ніва', vehicle_trademark_id: 18, vehicle_group_id: 3, wheel_count: 4 },
{ id: 189, name_en: 'LX 470', name_ua: 'LX 470', vehicle_trademark_id: 30, vehicle_group_id: 5, wheel_count: 4 },
{ id: 190, name_en: 'Pointer', name_ua: 'Поінтер', vehicle_trademark_id: 20, vehicle_group_id: 2, wheel_count: 4 },
{ id: 191, name_en: '407', name_ua: '407', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 192, name_en: 'Grandis', name_ua: 'Грандіс', vehicle_trademark_id: 9, vehicle_group_id: 4, wheel_count: 4 },
{ id: 193, name_en: 'Quattroporte', name_ua: 'Кватропорте', vehicle_trademark_id: 32, vehicle_group_id: 4, wheel_count: 4 },
{ id: 194, name_en: 'Cerato', name_ua: 'Cerato', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 195, name_en: 'Liana', name_ua: 'Ліана', vehicle_trademark_id: 33, vehicle_group_id: 2, wheel_count: 4 },
{ id: 196, name_en: 'Sorento', name_ua: 'Соренто', vehicle_trademark_id: 6, vehicle_group_id: 4, wheel_count: 4 },
{ id: 197, name_en: 'Trajet', name_ua: 'Траджет', vehicle_trademark_id: 23, vehicle_group_id: 4, wheel_count: 4 },
{ id: 198, name_en: 'Fusion', name_ua: 'Фьюжн', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 199, name_en: 'S 500 L ', name_ua: 'S 500 L ', vehicle_trademark_id: 8, vehicle_group_id: 5, wheel_count: 4 },
{ id: 200, name_en: 'XC90', name_ua: 'XC90', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 201, name_en: 'Discovery 3', name_ua: 'Діскавері 3', vehicle_trademark_id: 34, vehicle_group_id: 4, wheel_count: 4 },
{ id: 202, name_en: 'Micra', name_ua: 'Micra', vehicle_trademark_id: 10, vehicle_group_id: 2, wheel_count: 4 },
{ id: 203, name_en: 'Polo GP', name_ua: 'Polo GP', vehicle_trademark_id: 20, vehicle_group_id: 2, wheel_count: 4 },
{ id: 204, name_en: 'GX470', name_ua: 'GX470', vehicle_trademark_id: 30, vehicle_group_id: 5, wheel_count: 4 },
{ id: 205, name_en: 'ML 350', name_ua: 'ML 350', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 206, name_en: 'E220CDI', name_ua: 'E220CDI', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 207, name_en: 'Tavria', name_ua: 'Tavria', vehicle_trademark_id: 35, vehicle_group_id: 1, wheel_count: 4 },
{ id: 208, name_en: 'Sens', name_ua: 'Sens', vehicle_trademark_id: 3, vehicle_group_id: 2, wheel_count: 4 },
{ id: 209, name_en: 'T5 Shuttle', name_ua: 'T5 Shuttle', vehicle_trademark_id: 20, vehicle_group_id: 4, wheel_count: 4 },
{ id: 210, name_en: 'Transit Van', name_ua: 'Transit Van', vehicle_trademark_id: 4, vehicle_group_id: 5, wheel_count: 4 },
{ id: 211, name_en: 'Highlander ', name_ua: 'Highlander ', vehicle_trademark_id: 17, vehicle_group_id: 5, wheel_count: 4 },
{ id: 212, name_en: 'Z4', name_ua: 'Z4', vehicle_trademark_id: 2, vehicle_group_id: 5, wheel_count: 4 },
{ id: 213, name_en: 'Grand Vitara', name_ua: 'Grand Vitara', vehicle_trademark_id: 33, vehicle_group_id: 4, wheel_count: 4 },
{ id: 214, name_en: 'X-Type', name_ua: 'X-Type', vehicle_trademark_id: 36, vehicle_group_id: 4, wheel_count: 4 },
{ id: 215, name_en: 'Tucson', name_ua: 'Tucson', vehicle_trademark_id: 23, vehicle_group_id: 4, wheel_count: 4 },
{ id: 216, name_en: 'Jetta', name_ua: 'Jetta', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 217, name_en: 'А-09211 ', name_ua: 'А-09211 ', vehicle_trademark_id: 37, vehicle_group_id: 5, wheel_count: 4 },
{ id: 218, name_en: 'Accent', name_ua: 'Accent', vehicle_trademark_id: 23, vehicle_group_id: 2, wheel_count: 4 },
{ id: 219, name_en: 'Jazz', name_ua: 'Jazz', vehicle_trademark_id: 5, vehicle_group_id: 2, wheel_count: 4 },
{ id: 220, name_en: 'S500', name_ua: 'S500', vehicle_trademark_id: 8, vehicle_group_id: 5, wheel_count: 4 },
{ id: 221, name_en: 'Teana', name_ua: 'Teana', vehicle_trademark_id: 10, vehicle_group_id: 5, wheel_count: 4 },
{ id: 222, name_en: 'Cayenne', name_ua: 'Cayenne', vehicle_trademark_id: 38, vehicle_group_id: 4, wheel_count: 4 },
{ id: 223, name_en: 'A6 Allroad quattro', name_ua: 'A6 Allroad quattro', vehicle_trademark_id: 1, vehicle_group_id: 4, wheel_count: 4 },
{ id: 224, name_en: '530', name_ua: '530', vehicle_trademark_id: 2, vehicle_group_id: 4, wheel_count: 4 },
{ id: 225, name_en: 'E320 CDI', name_ua: 'E320 CDI', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 226, name_en: 'GS 300', name_ua: 'GS 300', vehicle_trademark_id: 30, vehicle_group_id: 4, wheel_count: 4 },
{ id: 227, name_en: 'RX-350 ', name_ua: 'RX-350 ', vehicle_trademark_id: 30, vehicle_group_id: 4, wheel_count: 4 },
{ id: 228, name_en: 'SX-4', name_ua: 'SX-4', vehicle_trademark_id: 33, vehicle_group_id: 4, wheel_count: 4 },
{ id: 229, name_en: 'Tourneo Connect', name_ua: 'Tourneo Connect', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 230, name_en: 'Yaris', name_ua: 'Yaris', vehicle_trademark_id: 17, vehicle_group_id: 2, wheel_count: 4 },
{ id: 231, name_en: 'Grand Vitara XL-7', name_ua: 'Grand Vitara XL-7', vehicle_trademark_id: 33, vehicle_group_id: 4, wheel_count: 4 },
{ id: 232, name_en: 'A3 Sportback', name_ua: 'A3 Sportback', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 233, name_en: 'Crafter', name_ua: 'Crafter', vehicle_trademark_id: 20, vehicle_group_id: 5, wheel_count: 4 },
{ id: 234, name_en: 'V50', name_ua: 'V50', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 235, name_en: 'Daily', name_ua: 'Daily', vehicle_trademark_id: 39, vehicle_group_id: 5, wheel_count: 4 },
{ id: 236, name_en: '300C', name_ua: '300C', vehicle_trademark_id: 40, vehicle_group_id: 5, wheel_count: 4 },
{ id: 237, name_en: 'Leon', name_ua: 'Leon', vehicle_trademark_id: 26, vehicle_group_id: 3, wheel_count: 4 },
{ id: 238, name_en: 'Epica', name_ua: 'Epica', vehicle_trademark_id: 27, vehicle_group_id: 4, wheel_count: 4 },
{ id: 239, name_en: 'Galaxy', name_ua: 'Galaxy', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 },
{ id: 240, name_en: 'S-Max', name_ua: 'S-Max', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 },
{ id: 241, name_en: 'Kyron', name_ua: 'Kyron', vehicle_trademark_id: 41, vehicle_group_id: 4, wheel_count: 4 },
{ id: 242, name_en: 'Q7', name_ua: 'Q7', vehicle_trademark_id: 1, vehicle_group_id: 5, wheel_count: 4 },
{ id: 243, name_en: 'Trafic Combi', name_ua: 'Trafic Combi', vehicle_trademark_id: 13, vehicle_group_id: 5, wheel_count: 4 },
{ id: 244, name_en: '318', name_ua: '318', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 245, name_en: '523', name_ua: '523', vehicle_trademark_id: 2, vehicle_group_id: 4, wheel_count: 4 },
{ id: 246, name_en: 'Legend', name_ua: 'Legend', vehicle_trademark_id: 5, vehicle_group_id: 5, wheel_count: 4 },
{ id: 247, name_en: 'Hummer', name_ua: 'Hummer', vehicle_trademark_id: 42, vehicle_group_id: 5, wheel_count: 4 },
{ id: 248, name_en: 'XC70 Cross Country', name_ua: 'XC70 Cross Country', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 250, name_en: 'Lanos Furgon', name_ua: 'Lanos Furgon', vehicle_trademark_id: 3, vehicle_group_id: 3, wheel_count: 4 },
{ id: 251, name_en: 'Outlander XL', name_ua: 'Outlander XL', vehicle_trademark_id: 9, vehicle_group_id: 4, wheel_count: 4 },
{ id: 252, name_en: 'Qashqai', name_ua: 'Qashqai', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 254, name_en: 'Cooper', name_ua: 'Cooper', vehicle_trademark_id: 43, vehicle_group_id: 2, wheel_count: 4 },
{ id: 255, name_en: 'Transit Connect', name_ua: 'Transit Connect', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 256, name_en: 'Freelander', name_ua: 'Freelander', vehicle_trademark_id: 34, vehicle_group_id: 4, wheel_count: 4 },
{ id: 257, name_en: 'Viano', name_ua: 'Viano', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 258, name_en: 'Roomster', name_ua: 'Roomster', vehicle_trademark_id: 15, vehicle_group_id: 2, wheel_count: 4 },
{ id: 259, name_en: 'Compass', name_ua: 'Compass', vehicle_trademark_id: 44, vehicle_group_id: 4, wheel_count: 4 },
{ id: 260, name_en: 'Caliber', name_ua: 'Caliber', vehicle_trademark_id: 45, vehicle_group_id: 4, wheel_count: 4 },
{ id: 261, name_en: 'Patrol', name_ua: 'Patrol', vehicle_trademark_id: 10, vehicle_group_id: 4, wheel_count: 4 },
{ id: 262, name_en: 'C 200 Compressor ', name_ua: 'C 200 Compressor ', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 263, name_en: 'R8', name_ua: 'R8', vehicle_trademark_id: 1, vehicle_group_id: 1, wheel_count: 4 },
{ id: 270, name_en: 'Fabia 07', name_ua: 'Fabia 07', vehicle_trademark_id: 15, vehicle_group_id: 2, wheel_count: 4 },
{ id: 271, name_en: 'GS 350 ', name_ua: 'GS 350 ', vehicle_trademark_id: 30, vehicle_group_id: 5, wheel_count: 4 },
{ id: 272, name_en: 'L 200', name_ua: 'L 200', vehicle_trademark_id: 9, vehicle_group_id: 4, wheel_count: 4 },
{ id: 273, name_en: 'Lancer X', name_ua: 'Lancer X', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 274, name_en: 'M35', name_ua: 'M35', vehicle_trademark_id: 46, vehicle_group_id: 5, wheel_count: 4 },
{ id: 275, name_en: 'G35', name_ua: 'G35', vehicle_trademark_id: 46, vehicle_group_id: 4, wheel_count: 4 },
{ id: 276, name_en: 'FX35', name_ua: 'FX35', vehicle_trademark_id: 46, vehicle_group_id: 5, wheel_count: 4 },
{ id: 277, name_en: 'Patriot ', name_ua: 'Patriot ', vehicle_trademark_id: 44, vehicle_group_id: 4, wheel_count: 4 },
{ id: 278, name_en: 'Range Rover Sport', name_ua: ' Range Rover Sport', vehicle_trademark_id: 34, vehicle_group_id: 5, wheel_count: 4 },
{ id: 279, name_en: '630i ', name_ua: '630i ', vehicle_trademark_id: 2, vehicle_group_id: 5, wheel_count: 4 },
{ id: 280, name_en: '325xi', name_ua: '325xi', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 281, name_en: 'Captiva', name_ua: 'Каптіва', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 282, name_en: 'TL', name_ua: 'TL', vehicle_trademark_id: 47, vehicle_group_id: 4, wheel_count: 4 },
{ id: 283, name_en: 'Cross Touran', name_ua: 'Cross Touran', vehicle_trademark_id: 20, vehicle_group_id: 4, wheel_count: 4 },
{ id: 284, name_en: 'Auris', name_ua: 'Auris', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 285, name_en: 'Altea ', name_ua: 'Altea ', vehicle_trademark_id: 26, vehicle_group_id: 3, wheel_count: 4 },
{ id: 286, name_en: 'FB15-12', name_ua: 'FB15-12', vehicle_trademark_id: 49, vehicle_group_id: 1, wheel_count: 4 },
{ id: 287, name_en: 'С30', name_ua: 'С30', vehicle_trademark_id: 19, vehicle_group_id: 3, wheel_count: 4 },
{ id: 288, name_en: '159 Sportwagon', name_ua: '159 Sportwagon', vehicle_trademark_id: 50, vehicle_group_id: 4, wheel_count: 4 },
{ id: 289, name_en: 'Tacuma', name_ua: 'Tacuma', vehicle_trademark_id: 27, vehicle_group_id: 3, wheel_count: 4 },
{ id: 290, name_en: 'Land Cruiser 200', name_ua: 'Land Cruiser 200', vehicle_trademark_id: 17, vehicle_group_id: 5, wheel_count: 4 },
{ id: 291, name_en: 'Focus`08', name_ua: 'Фокус`08', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 292, name_en: 'QX 56', name_ua: 'QX 56', vehicle_trademark_id: 46, vehicle_group_id: 5, wheel_count: 4 },
{ id: 293, name_en: 'Tiida', name_ua: 'Tiida', vehicle_trademark_id: 10, vehicle_group_id: 3, wheel_count: 4 },
{ id: 294, name_en: 'Avalon', name_ua: 'Avalon', vehicle_trademark_id: 17, vehicle_group_id: 5, wheel_count: 4 },
{ id: 295, name_en: 'JUMPY FG L1H1', name_ua: 'JUMPY FG L1H1', vehicle_trademark_id: 24, vehicle_group_id: 1, wheel_count: 4 },
{ id: 296, name_en: 'Forester`09', name_ua: 'Форестер`09', vehicle_trademark_id: 16, vehicle_group_id: 4, wheel_count: 4 },
{ id: 297, name_en: 'Rexton', name_ua: 'Rexton', vehicle_trademark_id: 41, vehicle_group_id: 4, wheel_count: 4 },
{ id: 298, name_en: 'C4', name_ua: 'C4', vehicle_trademark_id: 24, vehicle_group_id: 3, wheel_count: 4 },
{ id: 299, name_en: 'Ceed', name_ua: 'Ceed', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 300, name_en: 'escalade', name_ua: 'escalade', vehicle_trademark_id: 52, vehicle_group_id: 1, wheel_count: 4 },
{ id: 301, name_en: 'CX-7', name_ua: 'CX-7', vehicle_trademark_id: 7, vehicle_group_id: 4, wheel_count: 4 },
{ id: 302, name_en: '416', name_ua: '416', vehicle_trademark_id: 8, vehicle_group_id: 5, wheel_count: 4 },
{ id: 303, name_en: 'Carnival', name_ua: 'Carnival', vehicle_trademark_id: 6, vehicle_group_id: 4, wheel_count: 4 },
{ id: 304, name_en: 'Karry', name_ua: 'Karry', vehicle_trademark_id: 53, vehicle_group_id: 2, wheel_count: 4 },
{ id: 305, name_en: 'Hunter', name_ua: 'Hunter', vehicle_trademark_id: 54, vehicle_group_id: 4, wheel_count: 4 },
{ id: 306, name_en: 'Armada', name_ua: 'Armada', vehicle_trademark_id: 10, vehicle_group_id: 5, wheel_count: 4 },
{ id: 307, name_en: 'LS 460L', name_ua: 'LS 460L', vehicle_trademark_id: 30, vehicle_group_id: 5, wheel_count: 4 },
{ id: 308, name_en: 'Magentis ', name_ua: 'Magentis ', vehicle_trademark_id: 6, vehicle_group_id: 4, wheel_count: 4 },
{ id: 313, name_en: 'Doblo', name_ua: 'Doblo ', vehicle_trademark_id: 22, vehicle_group_id: 3, wheel_count: 4 },
{ id: 314, name_en: 'CX-9', name_ua: 'CX-9', vehicle_trademark_id: 7, vehicle_group_id: 4, wheel_count: 4 },
{ id: 315, name_en: 'Actyon', name_ua: 'Actyon', vehicle_trademark_id: 41, vehicle_group_id: 4, wheel_count: 4 },
{ id: 316, name_en: 'Q5', name_ua: 'Q5', vehicle_trademark_id: 1, vehicle_group_id: nil, wheel_count: 4 },
{ id: 318, name_en: 'Sequioa', name_ua: 'Sequioa', vehicle_trademark_id: 17, vehicle_group_id: 2, wheel_count: 4 },
{ id: 319, name_en: 'Pilot', name_ua: 'Pilot', vehicle_trademark_id: 5, vehicle_group_id: 3, wheel_count: 4 },
{ id: 321, name_en: 'Tiguan', name_ua: 'Tiguan', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 323, name_en: ' Logan', name_ua: ' Logan', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 326, name_en: 'Passat CC', name_ua: 'Пассат СС', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 327, name_en: 'Fluence', name_ua: 'Fluence', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 328, name_en: 'Logan MCV', name_ua: 'Logan MCV', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 329, name_en: 'GAZel 2705-226', name_ua: 'ГАЗель 2705-226', vehicle_trademark_id: 29, vehicle_group_id: 3, wheel_count: 4 },
{ id: 330, name_en: 'T5 Transporter', name_ua: 'T5 Transporter', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 331, name_en: 'Prado', name_ua: 'Prado', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 332, name_en: 'LX570', name_ua: 'LX570', vehicle_trademark_id: 30, vehicle_group_id: 4, wheel_count: 4 },
{ id: 333, name_en: 'T5 Kombi', name_ua: 'T5 Комби', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 334, name_en: 'Clio Symbol New', name_ua: 'Clio Symbol New', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 335, name_en: 'GAZel 330202-218', name_ua: 'GAZel 330202-218', vehicle_trademark_id: 29, vehicle_group_id: 3, wheel_count: 4 },
{ id: 336, name_en: 'Golf 6', name_ua: 'Гольф 6', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 337, name_en: 'XC60', name_ua: 'XC60', vehicle_trademark_id: 19, vehicle_group_id: 4, wheel_count: 4 },
{ id: 338, name_en: 'Kuga', name_ua: 'Kuga', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 339, name_en: 'GL500', name_ua: 'GL500', vehicle_trademark_id: 8, vehicle_group_id: 4, wheel_count: 4 },
{ id: 341, name_en: 'Terios', name_ua: 'Terios', vehicle_trademark_id: 57, vehicle_group_id: 4, wheel_count: 4 },
{ id: 342, name_en: 'Megane 3', name_ua: 'Megane 3', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 343, name_en: 'Mondeo New', name_ua: 'Mondeo New', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 },
{ id: 344, name_en: '207', name_ua: '207', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 345, name_en: '3008', name_ua: '3008', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 346, name_en: '308', name_ua: '308', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 347, name_en: 'Partner Tepee', name_ua: 'Partner Tepee', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 348, name_en: 'Logan Van', name_ua: 'Logan Van', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 349, name_en: 'Outback', name_ua: 'Аутбек', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 350, name_en: 'Astra J', name_ua: 'Astra J', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 352, name_en: 'Passat B7', name_ua: 'Passat B7', vehicle_trademark_id: 20, vehicle_group_id: 4, wheel_count: 4 },
{ id: 353, name_en: 'Range Rover', name_ua: 'Range Rover', vehicle_trademark_id: 34, vehicle_group_id: 5, wheel_count: 4 },
{ id: 354, name_en: 'Duster', name_ua: 'Duster', vehicle_trademark_id: 13, vehicle_group_id: 3, wheel_count: 4 },
{ id: 355, name_en: 'Latitude', name_ua: 'Dynamique', vehicle_trademark_id: 13, vehicle_group_id: 5, wheel_count: 4 },
{ id: 356, name_en: 'ASX', name_ua: 'ASX', vehicle_trademark_id: 9, vehicle_group_id: 3, wheel_count: 4 },
{ id: 357, name_en: 'T5', name_ua: 'T5', vehicle_trademark_id: 20, vehicle_group_id: 2, wheel_count: 4 },
{ id: 358, name_en: 'X-5 xDrive35i', name_ua: 'X-5 xDrive35i', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 359, name_en: 'Passat B7 Limousine', name_ua: 'Passat B7 Limousine', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 360, name_en: 'Insignia Sport Tourer', name_ua: 'Insignia Sport Tourer', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 370, name_en: 'Caddy GP', name_ua: 'Кеди ДжПи', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 372, name_en: 'Clio Symbol', name_ua: 'Sedan', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 373, name_en: 'Golf VI', name_ua: 'Golf VI', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 375, name_en: 'Yeti', name_ua: 'Yeti', vehicle_trademark_id: 15, vehicle_group_id: 2, wheel_count: 4 },
{ id: 376, name_en: 'Audi', name_ua: 'Ауді', vehicle_trademark_id: 1, vehicle_group_id: nil, wheel_count: 4 },
{ id: 380, name_en: 'A3 Base', name_ua: 'A3 Base', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 383, name_en: 'New Camry', name_ua: 'New Camry', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 394, name_en: 'IX-35', name_ua: 'IX-35', vehicle_trademark_id: 23, vehicle_group_id: 4, wheel_count: 4 },
{ id: 402, name_en: 'Rover', name_ua: 'Rover', vehicle_trademark_id: 61, vehicle_group_id: 5, wheel_count: 4 },
{ id: 413, name_en: 'S60 T4', name_ua: 'S60 T4', vehicle_trademark_id: 19, vehicle_group_id: 3, wheel_count: 4 },
{ id: 415, name_en: 'Insignia', name_ua: 'Insignia', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 417, name_en: 'LC Prado', name_ua: 'LC Prado', vehicle_trademark_id: 17, vehicle_group_id: 3, wheel_count: 4 },
{ id: 418, name_en: 'C3', name_ua: 'C3', vehicle_trademark_id: 24, vehicle_group_id: 3, wheel_count: 4 },
{ id: 419, name_en: 'Polo A5', name_ua: 'Polo A5', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 420, name_en: 'Passat Variant', name_ua: 'Passat Variant', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 421, name_en: 'Golf Plus', name_ua: 'Гольф Плюс', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 422, name_en: 'Master', name_ua: 'Мастер', vehicle_trademark_id: 13, vehicle_group_id: 5, wheel_count: 4 },
{ id: 423, name_en: 'T5GP', name_ua: 'T5GP', vehicle_trademark_id: 20, vehicle_group_id: 2, wheel_count: 4 },
{ id: 424, name_en: 'X1', name_ua: 'x1', vehicle_trademark_id: 2, vehicle_group_id: nil, wheel_count: 4 },
{ id: 425, name_en: 'Sandero', name_ua: 'Sandero', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 426, name_en: 'Amarok', name_ua: 'Amarok', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 427, name_en: 'HD-65', name_ua: 'HD-65', vehicle_trademark_id: 23, vehicle_group_id: 5, wheel_count: 6 },
{ id: 428, name_en: 'C5', name_ua: 'C5', vehicle_trademark_id: 24, vehicle_group_id: 3, wheel_count: 4 },
{ id: 429, name_en: 'Rio', name_ua: 'Rio', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 430, name_en: 'Benz', name_ua: 'Benz', vehicle_trademark_id: 8, vehicle_group_id: 3, wheel_count: 4 },
{ id: 431, name_en: '535iGT xD', name_ua: '535iGT xD', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 432, name_en: '408', name_ua: '408', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 434, name_en: 'Multivan T5GP', name_ua: 'Мультіван', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 436, name_en: 'Т5GP', name_ua: 'Т5GP', vehicle_trademark_id: 20, vehicle_group_id: 2, wheel_count: 4 },
{ id: 437, name_en: 'Quoris', name_ua: 'Quoris', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 438, name_en: 'Rapid', name_ua: 'Rapid', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 439, name_en: 'А-20110', name_ua: 'А-20110', vehicle_trademark_id: 62, vehicle_group_id: nil, wheel_count: 4 },
{ id: 440, name_en: 'C-Elysee', name_ua: 'C-Elysee', vehicle_trademark_id: 24, vehicle_group_id: 3, wheel_count: 4 },
{ id: 441, name_en: 'Grandeur', name_ua: 'Grandeur', vehicle_trademark_id: 23, vehicle_group_id: nil, wheel_count: 4 },
{ id: 442, name_en: 'B-Max', name_ua: 'B-Max', vehicle_trademark_id: 4, vehicle_group_id: nil, wheel_count: 4 },
{ id: 443, name_en: 'CC', name_ua: 'CC', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 444, name_en: 'Golf 7', name_ua: 'Golf 7', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 445, name_en: 'Mohave', name_ua: 'Mohave', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 446, name_en: '508', name_ua: '508', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 447, name_en: 'C-Max', name_ua: 'C-Max', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 },
{ id: 448, name_en: 'CX-5', name_ua: 'CX-5', vehicle_trademark_id: 7, vehicle_group_id: 4, wheel_count: 4 },
{ id: 449, name_en: 'Elantra MD', name_ua: 'Elantra MD', vehicle_trademark_id: 23, vehicle_group_id: 3, wheel_count: 4 },
{ id: 452, name_en: 'Octavia A7', name_ua: 'Октавія А7', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 453, name_en: '520i', name_ua: '520i', vehicle_trademark_id: 2, vehicle_group_id: nil, wheel_count: 4 },
{ id: 454, name_en: 'Astra H Caravan', name_ua: 'Astra H Caravan', vehicle_trademark_id: 11, vehicle_group_id: 3, wheel_count: 4 },
{ id: 455, name_en: 'Grand Cherokee', name_ua: 'Grand Cherokee', vehicle_trademark_id: 44, vehicle_group_id: nil, wheel_count: 4 },
{ id: 459, name_en: 'A7', name_ua: 'A7', vehicle_trademark_id: 1, vehicle_group_id: 5, wheel_count: 4 },
{ id: 460, name_en: 'X3', name_ua: 'X3', vehicle_trademark_id: 2, vehicle_group_id: 3, wheel_count: 4 },
{ id: 461, name_en: 'Connect Kombi', name_ua: 'Connect Kombi', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 462, name_en: 'Transit Kombi', name_ua: 'Transit Kombi', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 463, name_en: 'T5GP Kasten LR', name_ua: 'T5GP Kasten LR', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 464, name_en: 'XV', name_ua: 'XV', vehicle_trademark_id: 16, vehicle_group_id: 3, wheel_count: 4 },
{ id: 466, name_en: 'Transit Kombi F300MM', name_ua: 'Transit Kombi F300MM', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 467, name_en: 'Dokker Van', name_ua: 'Dokker Van', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 468, name_en: '508 RXH', name_ua: '508 RXH', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 469, name_en: '301', name_ua: '301', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 470, name_en: '750-131', name_ua: '750-131', vehicle_trademark_id: 63, vehicle_group_id: 1, wheel_count: 2 },
{ id: 471, name_en: 'A3 Limousine', name_ua: 'A3 Limousine', vehicle_trademark_id: 1, vehicle_group_id: 3, wheel_count: 4 },
{ id: 473, name_en: 'Octavia A7 Combi', name_ua: 'Octavia A7', vehicle_trademark_id: 15, vehicle_group_id: 3, wheel_count: 4 },
{ id: 474, name_en: 'I-30', name_ua: 'I-30', vehicle_trademark_id: 23, vehicle_group_id: nil, wheel_count: 4 },
{ id: 475, name_en: 'C1', name_ua: 'C1', vehicle_trademark_id: 24, vehicle_group_id: 1, wheel_count: 4 },
{ id: 476, name_en: '4008', name_ua: '4008', vehicle_trademark_id: 12, vehicle_group_id: nil, wheel_count: 4 },
{ id: 477, name_en: 'Cordoba', name_ua: 'Cordoba', vehicle_trademark_id: 26, vehicle_group_id: 3, wheel_count: 4 },
{ id: 478, name_en: 'Venza', name_ua: 'Venza', vehicle_trademark_id: 17, vehicle_group_id: nil, wheel_count: 4 },
{ id: 479, name_en: 'Dokker', name_ua: 'Dokker', vehicle_trademark_id: 13, vehicle_group_id: 2, wheel_count: 4 },
{ id: 480, name_en: '107', name_ua: '107', vehicle_trademark_id: 12, vehicle_group_id: 3, wheel_count: 4 },
{ id: 481, name_en: 'Korando', name_ua: 'Korando', vehicle_trademark_id: 41, vehicle_group_id: 4, wheel_count: 4 },
{ id: 482, name_en: 'Golf Sportsvan', name_ua: 'Golf Sportsvan', vehicle_trademark_id: 20, vehicle_group_id: nil, wheel_count: 4 },
{ id: 483, name_en: 'XF', name_ua: 'XF', vehicle_trademark_id: 36, vehicle_group_id: 4, wheel_count: 4 },
{ id: 484, name_en: 'Freemont', name_ua: 'Freemont', vehicle_trademark_id: 22, vehicle_group_id: 3, wheel_count: 4 },
{ id: 486, name_en: 'Fiesta MCA 2015 MY', name_ua: 'Фієста', vehicle_trademark_id: 4, vehicle_group_id: 2, wheel_count: 4 },
{ id: 487, name_en: 'Benz B', name_ua: 'Benz B', vehicle_trademark_id: 8, vehicle_group_id: nil, wheel_count: 4 },
{ id: 488, name_en: 'Benz ML', name_ua: 'Benz ML', vehicle_trademark_id: 8, vehicle_group_id: nil, wheel_count: 4 },
{ id: 489, name_en: 'Koleos', name_ua: 'Koleos', vehicle_trademark_id: 13, vehicle_group_id: nil, wheel_count: 4 },
{ id: 490, name_en: 'Ranger', name_ua: 'Ranger', vehicle_trademark_id: 4, vehicle_group_id: nil, wheel_count: 4 },
{ id: 491, name_en: 'Focus New', name_ua: 'Focus New', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 492, name_en: '500L', name_ua: '500L', vehicle_trademark_id: 22, vehicle_group_id: nil, wheel_count: 4 },
{ id: 493, name_en: 'Spaceback', name_ua: 'Spaceback', vehicle_trademark_id: 15, vehicle_group_id: nil, wheel_count: 4 },
{ id: 494, name_en: 'Transit Custom LWB', name_ua: 'Transit Custom LWB', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 496, name_en: 'Transit Van MWB', name_ua: 'Transit Van MWB', vehicle_trademark_id: 4, vehicle_group_id: 5, wheel_count: 4 },
{ id: 497, name_en: 'Sorento New', name_ua: 'Sorento New', vehicle_trademark_id: 6, vehicle_group_id: 3, wheel_count: 4 },
{ id: 499, name_en: 'T5 Multivan', name_ua: 'T5 Multivan', vehicle_trademark_id: 20, vehicle_group_id: 3, wheel_count: 4 },
{ id: 500, name_en: '520d', name_ua: '520d', vehicle_trademark_id: 2, vehicle_group_id: nil, wheel_count: 4 },
{ id: 502, name_en: 'Transit Custom Van', name_ua: 'Transit Custom Van', vehicle_trademark_id: 4, vehicle_group_id: 3, wheel_count: 4 },
{ id: 503, name_en: 'Mondeo 2015MY', name_ua: 'Mondeo 2015MY', vehicle_trademark_id: 4, vehicle_group_id: 4, wheel_count: 4 }])
